export const videos = [
  {
    id: 1,
    videoId: "Ava0duwBsZo",
    title: "Eminem - The Real Slim Shady (Official Video)",
    createdAt: new Date("2023-05-12").toISOString(),
  },
  {
    id: 2,
    videoId: "3JZ_D3ELwOQ",
    title: "Adele - Hello",
    createdAt: new Date("2022-11-21").toISOString(),
  },
  {
    id: 3,
    videoId: "ktvTqknDobU",
    title: "Imagine Dragons - Radioactive",
    createdAt: new Date("2023-03-08").toISOString(),
  },
  {
    id: 4,
    videoId: "hT_nvWreIhg",
    title: "OneRepublic - Counting Stars",
    createdAt: new Date("2022-07-14").toISOString(),
  },
  {
    id: 5,
    videoId: "JGwWNGJdvx8",
    title: "Ed Sheeran - Shape of You",
    createdAt: new Date("2023-09-01").toISOString(),
  },
  {
    id: 6,
    videoId: "60ItHLz5WEA",
    title: "Alan Walker - Faded",
    createdAt: new Date("2023-12-25").toISOString(),
  },
  {
    id: 7,
    videoId: "RgKAFK5djSk",
    title: "Wiz Khalifa - See You Again ft. Charlie Puth",
    createdAt: new Date("2024-01-15").toISOString(),
  },
  {
    id: 8,
    videoId: "fLexgOxsZu0",
    title: "Bruno Mars - 24K Magic",
    createdAt: new Date("2023-10-05").toISOString(),
  },
  {
    id: 9,
    videoId: "CevxZvSJLk8",
    title: "Katy Perry - Roar",
    createdAt: new Date("2022-09-22").toISOString(),
  },
  {
    id: 10,
    videoId: "09R8_2nJtjg",
    title: "Maroon 5 - Sugar",
    createdAt: new Date("2024-02-11").toISOString(),
  },
  {
    id: 11,
    videoId: "ZbZSe6N_BXs",
    title: "Pharrell Williams - Happy",
    createdAt: new Date("2023-04-20").toISOString(),
  },
  {
    id: 12,
    videoId: "kJQP7kiw5Fk",
    title: "Luis Fonsi - Despacito ft. Daddy Yankee",
    createdAt: new Date("2022-08-01").toISOString(),
  },
  {
    id: 13,
    videoId: "YQHsXMglC9A",
    title: "Adele - When We Were Young",
    createdAt: new Date("2024-03-14").toISOString(),
  },
  {
    id: 14,
    videoId: "OPf0YbXqDm0",
    title: "Mark Ronson - Uptown Funk ft. Bruno Mars",
    createdAt: new Date("2022-10-30").toISOString(),
  },
  {
    id: 15,
    videoId: "09R8_2nJtjg",
    title: "Maroon 5 - Sugar",
    createdAt: new Date("2024-01-05").toISOString(),
  },
  {
    id: 16,
    videoId: "NF-kLy44Hls",
    title: "NF - The Search",
    createdAt: new Date("2024-05-01").toISOString(),
  },
  {
    id: 17,
    videoId: "nYh-n7EOtMA",
    title: "Charlie Puth - Attention",
    createdAt: new Date("2022-12-18").toISOString(),
  },
  {
    id: 18,
    videoId: "SlPhMPnQ58k",
    title: "Maroon 5 - Memories",
    createdAt: new Date("2023-08-10").toISOString(),
  },
  {
    id: 19,
    videoId: "0KSOMA3QBU0",
    title: "Sia - Chandelier",
    createdAt: new Date("2023-06-02").toISOString(),
  },
  {
    id: 20,
    videoId: "bESGLojNYSo",
    title: "Doja Cat - Say So",
    createdAt: new Date("2024-04-12").toISOString(),
  },
  {
    id: 21,
    videoId: "IcrbM1l_BoI",
    title: "Glass Animals - Heat Waves",
    createdAt: new Date("2023-02-14").toISOString(),
  },
  {
    id: 22,
    videoId: "2vjPBrBU-TM",
    title: "Sia - Elastic Heart",
    createdAt: new Date("2022-06-10").toISOString(),
  },
  {
    id: 23,
    videoId: "VYOjWnS4cMY",
    title: "Childish Gambino - This Is America",
    createdAt: new Date("2023-11-20").toISOString(),
  },
  {
    id: 24,
    videoId: "pRpeEdMmmQ0",
    title: "Shakira - Waka Waka (This Time for Africa)",
    createdAt: new Date("2024-05-27").toISOString(),
  }
]
